const RESUME_CHECK_LIST_DO_QUESTIONS = [
  "Understand the distinctions between a CV and a resume.",
  "Customize your resume for each job application.",
  "Highlight pertinent skills and experiences.",
  "Ensure clarity and brevity in your language.",
  "Provide accurate personal contact information.",
  "Showcase your achievements and successes.",
  "Quantify your experiences wherever feasible.",
  "Employ action verbs to detail your responsibilities.",
  "Format your resume for readability and consistency.",
  "Prioritize relevant information over minor details.",
  "Use a professional email address for correspondence.",
  "Include a link to your LinkedIn profile.",
  "Proofread your resume meticulously for errors.",
  "Seek feedback from peers or mentors for improvement.",
  "Utilize a reverse chronological format for work history.",
  "Include relevant education and certifications.",
  "Highlight leadership or team-oriented experiences.",
  "Tailor your resume to fit the job description.",
  "Incorporate industry-specific keywords from job description (JD) for visibility.",
  "Demonstrate adaptability and willingness to learn.",
  "Quantify the impact of your contributions.",
  "Provide examples of problem-solving abilities.",
  "Include relevant technical skills and proficiencies.",
  "Employ bullet points for readability and clarity.",
  "Keep your resume concise, ideally to one or two pages.",
  "Highlight relevant volunteer work to draw attention to leadership skills.",
  "Emphasize your ability to collaborate effectively.",
  "Showcase your project management skills.",
  "Include relevant industry affiliations or memberships.",
  "Demonstrate strong written and verbal communication skills.",
  "Opt for a clean and professional design layout.",
  "Prioritize information aligned with the job requirements as in JD",
  "Include a succinct summary of skills and qualifications at the top.",
  "Incorporate skills from job description (JD) for visibility.",
  "Highlight your ability to meet deadlines efficiently.",
  "Provide quantifiable achievements and outcomes.",
  "Customize your resume for different industries and different companies, if needed.",
  "Include a professional summary or objective statement.",
  "Enumerate relevant software proficiencies.",
  "Incorporate any pertinent publications or presentations.",
  "Illustrate your ability to adapt to diverse work environments.",
  "Maintain consistent formatting throughout the resume.",
  "Highlight any relevant awards, external recognition or honors received.",
  "Showcase your problem-solving skills through examples.",
  "Specify any language proficiencies relevant to the role.",
  "List any relevant professional development or training undertaken.",
  "Include measurable results to underscore your contributions.",
  "Demonstrate your capacity to work autonomously.",
  "Showcase your enthusiasm and passion for the industry.",
  "Keep your resume up-to-date with your latest experiences and achievements.",
];
const RESUME_CHECK_LIST_DONT_QUESTIONS = [
  "Avoid including irrelevant personal details (e.g., marital status, age).",
  "Refrain from using unprofessional email addresses.",
  "Omit photos of yourself from your resume.",
  "Steer clear of jargon or technical terms that may confuse readers.",
  "Avoid excessive formatting or decorative elements.",
  "Refrain from using slang or informal language.",
  "Do not exaggerate or embellish your experiences.",
  "Exclude unnecessary or outdated skills.",
  "Avoid mentioning salary expectations or requirements.",
  "Refrain from using generic templates without customization.",
  "Avoid using abbreviations or acronyms without explanation.",
  "Refrain from including references on your resume; offer them upon request.",
  "Avoid overly complex language or vocabulary.",
  "Do not include information about hobbies or interests unless relevant.",
  "Omit controversial or sensitive topics.",
  "Avoid using a font size smaller than 10 pt.",
  "Refrain from using multiple fonts or colors.",
  "Avoid including negative or irrelevant information.",
  "Exclude high school education unless recent or relevant.",
  "Avoid listing every task or duty; focus on achievements.",
  "Refrain from using passive language; use active verbs instead.",
  "Do not include unexplained gaps in employment. If more than 6 months, address that in cover letter",
  "Avoid using personal pronouns (e.g., “I,” “me,” “my”).",
  "Omit irrelevant coursework or projects.",
  "Refrain from including irrelevant certifications or training.",
  "Avoid listing outdated or irrelevant professional affiliations.",
  "Omit overly personal details or anecdotes.",
  "Avoid using unprofessional language or tone.",
  "Refrain from including irrelevant volunteer experiences.",
  "Avoid listing references without their permission.",
  "Omit irrelevant or outdated contact information.",
  "Avoid using overly casual or informal language.",
  "Exclude unrelated skills or experiences.",
  "Refrain from including unrelated extracurricular activities.",
  "Avoid using generic buzzwords or cliches.",
  "Omit irrelevant social media profiles. Avoid mentioning instagram, facebook, twitter and tiktok profiles",
  "Refrain from using overly long or complicated sentences.",
  "Avoid mentioning salary information from previous jobs.",
  "Refrain from using unprofessional email signatures.",
  "Omit outdated software skills.",
  "Avoid using unexplained abbreviations or industry-specific terms.",
  "Refrain from including irrelevant achievements or awards.",
  "Avoid using non-standard file formats for your resume. Stick to pdf",
  "Omit irrelevant training or certifications.",
  "Avoid using unprofessional or outdated fonts. Use Calibri, Times New Roman and other safe fonts",
  "Use a 2 page resume only if you have experience more than 12 years. Do not go to 3 pages and more",
  "Avoid using unexplained acronyms.",
  "Omit irrelevant professional references.",
  "Avoid using humor or sarcasm in your resume.",
  "Steer clear of overcrowding your resume with unnecessary details.",
];

const BRANCH_SELECTION_UG_QUESTIONS = [
  "Are you interested in a career in designing medical and drug delivery devices such as pacemakers and insulin pumps?",
  "Are you interested in a career in every aspect of product design from start to finish?",
  "Are you interested in a career in designing and building mechanisms like vehicles and engines?",
  "Are you interested in a career in advanced mechanics, like aerodynamics and combustion of gases?",
  "Are you interested in a career in conducting experiments to develop a deeper understanding of nature and the cosmos?",
  "Are you interested in a career in using mathematics to reveal the inner workings of nature and expand our knowledge of the universe?",
  "Are you interested in a career in manipulating current materials, and creating new ones to meet and exceed societal needs?",
  "Are you interested in a career in designing indoor and outdoor environments that are healthy and sustainable?",
  "Are you interested in a career in developing technology to treat brain and nervous system disorders such as Alzheimer's, dementia, depression, or Tourette's syndrome?",
  "Are you interested in a career in making farming more sustainable?",
  "Are you interested in a career in the manufacture of food products and pharmaceutical drugs?",
  "Are you interested in a career in generating, distributing, and optimizing the use of clean electrical power?",
  "Are you interested in a career in designing sustainable structures, the world's tallest buildings, and world-famous bridges?",
  "Are you interested in a career in optimizing performance and reducing the cost of technical and business systems?",
  "Are you interested in a career in developing new consumer products (e.g., shampoo, ice cream, vaccines) for large-scale production?",
  "Are you interested in a career in finding solutions to unmet challenges in biology, health and medicine?",
  "Are you interested in a career in optimizing processes in manufacturing, health care, and other industries?",
  "Are you interested in a career in creating solutions that protect our drinking water, fresh air, soil, and climate?",
  "Are you interested in a career in developing spacecrafts or new technologies to advance space travel?",
  "Are you interested in a career in designing and building computers and combining hardware and software to create an end product?",
  "Are you interested in a career in radiological applications for medical diagnosis, cancer treatment, and national security and defense?",
  "Are you interested in a career in solving complex mathematical and theoretical problems?",
  "Would you like to have a career where you work with circuits, their components, and their applications (e.g., robotics, sensors, biomedical instruments, and communication devices)?",
  "Would you like to have a career where you identify and process the necessary materials to advance our technologies in a way that is environmentally sustainable?",
  "Would you like to have a career where you use data analysis and computer modeling to optimize robot components (e.g., minimizing material and maximizing strength)?",
  "Would you like to have a career where you develop new sources of renewable energy?",
  "Would you like to have a career where you use elements of the environment to aid in construction design?",
  "Would you like to have a career where you develop technical solutions to process medical images, genetic codes, and cellular data?",
  "Would you like to have a career where you make manufacturing processes (e.g., for chemicals and oil) more efficient, clean, and sustainable?",
  "Would you like to have a career where you improve how people interact with technology, work and home environments, and information?",
  "Would you like to have a career where you understand why some materials are strong, compatible with the human body, shape-changing, or even magnetic?",
  "Would you like to have a career where you learned in college how plasmas (ionized gases) can make your cell phones and laptops smaller, cheaper, and faster?",
  "Would you like to have a career where you develop complex vehicles by combining new materials, propulsion, controls, and other systems?",
  "Would you like to have a career where you studied engineering design in college and had the flexibility to choose a specialty (e.g., robotics, automotive engineering, bioengineering, business, computer science, or environmental quality)?",
  "Would you like to have a career where you uncover relationships within large sets of data to understand real world problems and make decisions?",
  "Would you like to have a career where you develop specialized hardware for applications like artificial intelligence, machine learning, computer security, and data science?",
  "Would you like to have a career where you design an aircraft to improve air transportation?",
  "Would you like to have a career where you reimagine the roads, rails, bridges, waterways, and other infrastructure to transport goods and people?",
  "Would you like to have a career where you explored in college how to use clean, reliable, and safe nuclear-generated electricity as a green energy solution?",
  "Would you like to have a career where you studied the fundamental interactions of matter, energy, space, and time in college to solve scientific mysteries?",
  "Would you like to have a career where you work with computers at every level - circuits, hardware, software, and networks?",
  "Would you like to have a career where you used computers to analyze large data sets to help better understand why things happen the way they do in the world and in the universe?",
  "Would you like to have a career where you learned in college how different energies (like heat) and fluids (like air, water, and fuel) move and change?",
  "Would you like to have a career where you gained a broad understanding in college of the manufacture, assembly, and control of robots and other devices?",
  "Would you like a career developing technical tools (using nothing more than a computer and internet access) that will assist, inform, entertain, and excite people around the world?",
  "Are you really intrigued by communication and data exchange using wireless, optical, or quantum technologies?",
  "Do you like mathematical proofs and computational modeling of physical systems?",
  "Do you have a strong passion for improving the health and wellbeing of people?",
  "Do you have a real interest in the analytics of finance and economic information?",
];

const BRANCH_SELECTION_UG_CONFIG = {
  CS:[4,6,3,4,7,9,5,3,5,2,3,4,2,7,4,5,6,3,5,10,3,10,7,4,9,5,2,7,4,8,5,6,4,8,10,10,5,3,4,7,10,10,5,7,10,8,10,3,9],
  IT:[3,5,2,3,6,8,4,2,4,1,2,3,1,8,3,4,5,2,4,9,2,9,6,3,8,4,1,6,3,9,4,5,3,7,9,9,4,2,3,6,9,9,4,6,9,7,9,2,10],
  ECE:[8,7,5,6,5,7,6,4,7,4,5,9,3,5,6,6,7,4,7,8,6,8,10,5,7,7,3,9,5,6,6,10,7,9,6,8,7,4,7,8,8,6,6,9,6,10,8,5,5],
  EE:[7,8,4,5,4,6,3,5,6,3,4,10,4,6,5,3,8,5,6,7,5,7,9,6,6,8,4,8,6,7,3,9,6,6,7,7,6,5,8,9,7,5,7,8,5,9,7,4,4],
  Mech:[9,10,10,8,3,5,7,6,8,5,6,7,5,9,7,7,9,6,8,5,7,6,8,7,10,6,5,5,7,5,7,7,10,10,4,5,8,6,6,5,5,4,10,10,4,5,6,6,3],
  Prod:[6,9,7,2,2,4,8,7,3,6,7,8,6,10,8,2,10,7,3,4,4,5,5,8,5,3,6,4,10,4,8,4,8,5,3,4,3,7,5,4,4,3,8,5,3,4,5,1,6],
  Chem:[2,4,1,1,8,3,10,8,2,9,10,6,7,4,10,8,4,10,1,3,8,4,4,10,3,9,7,3,9,3,10,3,2,4,2,3,2,1,9,3,3,7,9,3,2,3,4,7,7],
  Bio:[10,3,6,7,9,2,9,9,10,10,9,5,8,3,9,10,3,9,2,2,10,3,3,9,4,10,8,10,8,2,9,2,5,3,1,2,1,8,10,2,2,8,3,4,1,2,3,10,8],
  Aero:[5,2,9,10,10,1,2,1,9,8,1,2,9,2,2,9,2,8,10,6,9,2,2,2,2,2,9,2,2,1,2,8,9,2,5,6,10,9,2,1,6,2,2,2,7,6,2,9,2],
  Civil:[1,1,8,9,1,10,1,10,1,7,8,1,10,1,1,1,1,1,9,1,1,1,1,1,1,1,10,1,1,10,1,1,1,1,8,1,9,10,1,10,1,1,1,1,8,1,1,8,1],
}


export { RESUME_CHECK_LIST_DO_QUESTIONS, RESUME_CHECK_LIST_DONT_QUESTIONS, BRANCH_SELECTION_UG_QUESTIONS, BRANCH_SELECTION_UG_CONFIG };
